### ISSUE TITLE
post_build.rs always builds for the cross-compiled target

### ISSUE THREAD

**Issue by tfinnegan937** [phil-opp/cargo-post#26]
I am currently building a cross-compiled aarch64-unknown-none application. I would like to use post_build.rs to specify some additional post-build linker commands.

I have the following config.toml in my project:

```toml
[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=linker.ld"]
```

This specifies the target as aarch64-unknown-none while building. 

When I define a build.rs script, cargo is intelligent enough to know NOT to build build.rs for the aarch64-unknown-none target. Instead, it uses my host machine's triple.

post_build.rs, however, appears to be built for the project's build target. This makes the post_build executable unable to run on on my host, rendering it unusable.

In this case, I would expect cargo post build to build post_build.rs for my host triple, NOT the target triple for the overall project.
