### ISSUE TITLE
Local dependent crate is not found

### ISSUE THREAD

**Issue by virtualritz** [phil-opp/cargo-post#4]
From my `Cargo.toml`:
```toml
[package.metadata.cargo-post.dependencies]
depgraph = "0.3.0"
aftereffects-sys = { path = "../crates/aftereffects-sys" }

[dependencies]
aftereffects-sys = { path = "../crates/aftereffects-sys" }
```

`depgraph` is found, `aftereffects-sys` is not found by `cargo post` (but found by `cargo`).

As you can see the location of this crate for the `package.metadata.cargo-post.dependencies` section is specified matching that of the `dependencies` one exactly.

**Comment by phil-opp** [comment]
Thanks for reporting! I opened #6 with a fix. Can you try whether it works for you? To install the new version, use:

```
cargo install cargo-post --debug --force --git https://github.com/phil-opp/cargo-post.git --branch  fix-local-deps
```

**Comment by virtualritz** [comment]
Sorry, about the delay. Just got to try this. I get an error now:
```terminal
Running Post Build Script at /Users/moritz/code/NeoNoise/post_build.rs
error: failed to parse manifest at `/Users/moritz/code/NeoNoise/target/post_build_script_manifest/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  redefinition of table `dependencies` for key `dependencies` at line 11 column 1
```
So looking at the culprit:
```terminal
❯ cat /Users/moritz/code/NeoNoise/target/post_build_script_manifest/Cargo.toml
[package]
name = "post-build-script"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "post-build-script"
path = "/Users/moritz/code/NeoNoise/post_build.rs"

[dependencies]
[dependencies]
depgraph = "0.3.0"
itertools = "0.9.0"

[dependencies.aftereffects-sys]
path = "/Users/moritz/code/crates/aftereffects-sys"
```

**Comment by virtualritz** [comment]
Ah yes, my `Cargo.toml`, just in case:
````toml
[package]
name = "neo_noise"
version = "0.1.1"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
description = "The last AfterEffects plug-in to generate noise you ever need"

[lib]
name = "NeoNoise"
prefix = ""
crate-type = ["cdylib"]

[package.metadata.bundle]
name = "NeoNoise"
identifier = "com.summae.AfterEffects.NeoNoise"
type = "AEgx"
copyright = "© 2020 Moritz Moeller"

#icon = []
[package.metadata.cargo-post.dependencies]
depgraph = "0.3.0"
itertools = "0.9.0"
aftereffects-sys = { path = "../crates/aftereffects-sys" }

[dependencies]
aftereffects-sys = { path = "../crates/aftereffects-sys" }
color-backtrace = "0.4.2"
simdnoise = { path = "../rust-simd-noise" }
#chrono = "0.4.11"
exr = "0.7.4"
function_name = "0.2.0"
fxhash = "0.2.1"
image = "0.23.4"
#lazy_static = "1.4.0"
libc = "0.2.70"
log4rs = "0.12.0"
log = "0.4.8"
nalgebra = "0.21.0"
ndspy-sys = { path = "../crates/ndspy-sys" }
nsi = { path = "../crates/nsi" }
num = "0.2.1"
palette = "0.5.0"
#serde = { version = "1.0.106", features = ["derive"] }
#syslog = "*"
rayon = "1.3.0"

#widestring = "0.4.0"
[dependencies.aftereffects]
path = "../crates/aftereffects"
features = ["algebra-nalgebra"]

[dependencies.log-panics]
version = "2.0.0"
features = ["with-backtrace"]

[profile.release]
debug = true
lto = "on"
opt-level = 3
rpath = false
panic = "unwind"

```
